name: ci
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  deploy-pages:
    # Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          pipx install poetry
          poetry install
          git fetch origin gh-pages --depth=1
          poetry run mike deploy ${{  github.ref_name }} latest -u -p
