name: ci
on: push
permissions:
  contents: write
jobs:

  run-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-repository
      - name: 'Run black'
        run: poetry run black src/
      - name: 'Run flake8'
        run: poetry run flake8 src/
      - name: 'Run isort'
        run: poetry run isort src/

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: run-formatting
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-repository
      - name: 'Run unit-tests'
        run: poetry run pytest tests/unit-tests --cov=src/ --cov-report=term:skip-covered --cov-report=xml:coverage.xml --junitxml=pytest-junit.xml
      - name: 'Pytest coverage comment'
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest-junit.xml

  deploy-pages:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-repository
      - name: 'Deploy to pages with mike'
        run: |
          git fetch origin gh-pages --depth=1
          poetry run mike deploy ${{  github.ref_name }} latest -u -p
